import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-companies',
  templateUrl: './companies.component.html',
  styleUrls: ['./companies.component.scss'],
})
export class CompaniesComponent {
  tableThInformation = [
    {
      symbol: 'MT',
      companyName: 'ArcelorMittal S.A.',
      industry: 'Extract & Mine Proc.',
      price: '29.43',
      esgScore: '85/100',
      eps: '10.18',
      esgRisk: '36.9 - H',
    },
    {
      symbol: 'AAPL',
      companyName: 'Apple Inc.',
      industry: 'Tech & Com',
      price: '146.71',
      esgScore: '80/100',
      eps: '5.78',
      esgRisk: '16.7 - L',
    },
    {
      symbol: 'DAR',
      companyName: 'Darling Ingredients Inc.',
      industry: 'Food & Beverage',
      price: '66.97',
      esgScore: '71/100',
      eps: '4.44',
      esgRisk: '22.3 - M',
    },
    {
      symbol: 'GS',
      companyName: 'Goldman Sachs Group, Inc.',
      industry: 'Financials',
      price: '363.85',
      esgScore: '85/100',
      eps: '30.5',
      esgRisk: '25.8 - M',
    },
    {
      symbol: 'LIN',
      companyName: 'Linde PLC',
      industry: 'Resource Transformation',
      price: '347.66',
      esgScore: '92/100',
      eps: '8.24',
      esgRisk: '8.2 - N',
    },
    {
      symbol: 'EXPO',
      companyName: 'Exponent, Inc.',
      industry: 'Services',
      price: '103.63',
      esgScore: '26/100',
      eps: '1.96',
      esgRisk: '20.1 - M',
    },
    {
      symbol: 'CCK',
      companyName: 'Crown Holdings, Inc.',
      industry: 'Resource Transformation',
      price: '85.58',
      esgScore: '71/100',
      eps: '6.09',
      esgRisk: '10.4 - L',
    },
    {
      symbol: 'ASGN',
      companyName: 'ASGN Inc.',
      industry: 'Services',
      price: '88.42',
      esgScore: '67/100',
      eps: '5.22',
      esgRisk: '13.8 - L',
    },
    {
      symbol: 'ETN',
      companyName: 'Eaton Corporation PLC',
      industry: 'Infrastructure',
      price: '173.25',
      esgScore: '71/100',
      eps: '6.13',
      esgRisk: '17.9 - L',
    },
    {
      symbol: 'NVDA',
      companyName: 'NVIDIA Corporation',
      industry: 'Tech & Com',
      price: '232.86',
      esgScore: '79/100',
      eps: '2.35',
      esgRisk: '13.6 - L',
    },
    {
      symbol: 'AFG',
      companyName: 'American Financial Group, Inc.',
      industry: 'Financials',
      price: '132.95',
      esgScore: '42/100',
      eps: '10.76',
      esgRisk: '28.8 - M',
    },
    {
      symbol: 'VSTO',
      companyName: 'Vista Outdoor Inc.',
      industry: 'Consumer Goods',
      price: '28.50',
      esgScore: '66/100',
      eps: '6.66',
      esgRisk: '16.3 - L',
    },
    {
      symbol: 'ABT',
      companyName: 'Abbott Laboratories',
      industry: 'Healthcare',
      price: '100.46',
      esgScore: '83/100',
      eps: '3.83',
      esgRisk: '25.0 - M',
    },
    {
      symbol: 'MATX',
      companyName: 'Matson, Inc.',
      industry: 'Transportation',
      price: '67.71',
      esgScore: '60/100',
      eps: '27.34',
      esgRisk: '19.3 - L',
    },
    {
      symbol: 'CMG',
      companyName: 'Chipotle Mexican Grill, Inc.',
      industry: 'Food & Beverage',
      price: '1,476.73',
      esgScore: '63/100',
      eps: '31.36',
      esgRisk: '23.5 - M',
    },
    {
      symbol: 'AVY',
      companyName: 'Avery Dennison Corporation',
      industry: 'Consumer Goods',
      price: '181.65',
      esgScore: '70/100',
      eps: '9.21',
      esgRisk: '15.4 - L',
    },
    {
      symbol: 'SHEL',
      companyName: 'Shell PLC',
      industry: 'Extract & Mine Proc.',
      price: '60.63',
      esgScore: '93/100',
      eps: '11.42',
      esgRisk: '37.6 - H',
    },
    {
      symbol: 'WM',
      companyName: 'Waste Management, Inc',
      industry: 'Infrastructure',
      price: '151.31',
      esgScore: '85/100',
      eps: '5.40',
      esgRisk: '16.8 - L',
    },
    {
      symbol: 'DHR',
      companyName: 'Danaher Corporation',
      industry: 'Healthcare',
      price: '249.12',
      esgScore: '82/100',
      eps: '9.67',
      esgRisk: '11.9 - L',
    },
    {
      symbol: 'JHBT',
      companyName: 'J.B. Hunt Transport Services',
      industry: 'Transportation',
      price: '183.54',
      esgScore: '74/100',
      eps: '9.14',
      esgRisk: '14.7 - L',
    },
  ];

  constructor(private router: Router) {}

  onRedirect() {
    this.router.navigateByUrl('companies/microsoft');
  }
}
